### ISSUE TITLE
bee not doing hot updates

### ISSUE THREAD

**Issue by justinfx** [astaxie/bee#14]
I'm having no trouble getting my first project up and running with beego, and I just started to test `bee` for the hot update feature. But I seem to be having problems, where it does not restart the process, or auto rebuild.  Maybe I am not doing correctly...

Platform: OSX

```
$ cd /path/to/my/src/myProject
$ ~/bin/bee start /path/to/my/src/myProject/myProject
/path/to/my/src/myProject/controllers
/path/to/my/src/myProject/models
start autobuild
build success
start /path/to/my/src/myProject/myProject
```

That launches the process and I can successfully use the exposed GET endpoints. But when I change any source code, I don't see it say it is rebuilding and restarting the process. And when I send it a SIGHUP, like in your README example, it simply kills the myProject process, leaving bee still running. I can no longer hit the GET endpoints anymore.

Am I running `bee start` correctly? Should it be run from within the project directory, and passed the full path to the executable?

**Comment by justinfx** [comment]
Also, I have been looking at this a little more and just noticed that `bee` is using a consistant 85% of my cpu, while doing nothing. Something must be wrong.

**Comment by astaxie** [comment]
1.  I think you have mixed HotUpdate and autobuild.
    bee start is autobuild. And this is for develop.
    send s SIGHUP is for product for hotupdate.
2. I use like this: `bee start ./beeadmin`  and I have test in my mac like 

``` Go
astaxie:beeadmin astaxie$ bee start ./beeadmin
/Users/astaxie/Yunio/gopath/src/beeadmin/controllers
/Users/astaxie/Yunio/gopath/src/beeadmin/models
start autobuild
build success
start ./beeadmin
"/Users/astaxie/Yunio/gopath/src/beeadmin/controllers/.sublb11.tmp": CREATE
"/Users/astaxie/Yunio/gopath/src/beeadmin/controllers/.sublb11.tmp": MODIFY
start autobuild
"/Users/astaxie/Yunio/gopath/src/beeadmin/controllers/default.go": MODIFY
"/Users/astaxie/Yunio/gopath/src/beeadmin/controllers/default.go": DELETE
"/Users/astaxie/Yunio/gopath/src/beeadmin/controllers/default.go": CREATE
"/Users/astaxie/Yunio/gopath/src/beeadmin/controllers/default.go": MODIFY
"/Users/astaxie/Yunio/gopath/src/beeadmin/controllers/.sublb11.tmp": MODIFY
build success
start ./beeadmin
start autobuild
```

and my cpu info is very low. Not like you say.

**Comment by astaxie** [comment]
hi,is it now bee fix your problem

**Comment by justinfx** [comment]
Ah. I ended up switching over to Revel so I haven't tried bee since this issue. Just updated my install and see that the framework has been updated a bit (run instead of start). I don't have the original test project I tried with bee, but the hello app seems to work just fine.
Thanks!
