### ISSUE TITLE
bee install error

### ISSUE THREAD

**Issue by fengqi** [astaxie/bee#18]
# github.com/astaxie/bee

/usr/lib/go/src/pkg/github.com/astaxie/bee/pack.go:264: undefined: tar.FileInfoHeader
/usr/lib/go/src/pkg/github.com/astaxie/bee/pack.go:362: cw.Flush undefined (type *gzip.Writer has no field or method Flush)

why?

**Comment by slene** [comment]
make sure your go version is 1.1+

**Comment by fengqi** [comment]
ok
