### ISSUE TITLE
执行main.go时出错

### ISSUE THREAD

**Issue by davidhhuan** [astaxie/bee#3]
刚接触golang，如果是比较2B的问题，还请见谅！

cd到代码目录，执行

```
go run main.go
```

得到以下错误：

```
# command-line-arguments
./main.go:59: undefined: cmdCreate
./main.go:60: undefined: cmdStart
```

请问有哪个步骤遗漏了？谢谢～

**Comment by astaxie** [comment]
你安装出错了，应该是这样安装
`go get github.com/astaxie/bee`

这样就已经安装好bee工具了，在gopath/bin下面已经有bee二进制运行文件，只要你把这个目录加入了你的path你就可以在你的命令行运行了，不是你这样运行的，明白？

**Comment by davidhhuan** [comment]
果然是这样子。。。囧

感谢您的热心回答

**Comment by davidhhuan** [comment]
Hi, again.

使用命令创建了一个项目

```
bee create beela
```

进行了beela目录，然后执行

```
bee start beela
```

报了如下错误：

```
/home/davidhhuan/go/src/beela/controllers
/home/davidhhuan/go/src/beela/models
start beela
cmd start: exec: "beela": executable file not found in $PATH
```

请问这是什么问题呢？

**Comment by astaxie** [comment]
不是提示你了嘛，找不到beela可执行文件，你要先go build啊

**Comment by davidhhuan** [comment]
囧。。。我build错了

我原来用

```
go build main.go
```

。。。

应该直接在文件夹下面build

```
go build
```
