### ISSUE TITLE
bee Windows环境下路径错误

### ISSUE THREAD

**Issue by ipfans** [astaxie/bee#31]
go get github.com/astaxie/bee

之后应该是路径原因创建了

C:\go\bin; 目录，并将 bee.exe拷贝到了该目录

应该是在处理环境变量时有点问题

**Comment by astaxie** [comment]
没看明白你的意思。。。？

**Comment by ipfans** [comment]
@astaxie 就是本来应该放在C:\go\bin目录下，但是只是单纯从环境变量中读出来路径拼起来了，多了一个分号，目录名字不对了

如图，bee.exe放在那个带;号的目录了
![图片](http://ww3.sinaimg.cn/large/935902a9gw1e8kv9nk0djj207g03z3ye.jpg)

**Comment by astaxie** [comment]
我还是没明白你说的意思

**Comment by ipfans** [comment]
@astaxie 本来应该放入上面那个没有分号目录的，bee.exe存放的路径不对 =_,=

**Comment by astaxie** [comment]
bee.exe怎么会到你的bin;目前去啊？
我没搞懂啊？
go get安装的话都会到gopath/bin下面去啊
