### ISSUE TITLE
bee test/go test时beego.AppConfig失效

### ISSUE THREAD

**Issue by meilihao** [astaxie/bee#38]
运行bee test app/go test时发现beego.AppConfig.String()无法加载参数(conf/app.conf中已存在该节点和值),而运行bee run app时程序又能正常加载运行,不知是怎么回事.
![qq20131128162649](https://f.cloud.github.com/assets/4382586/1638265/41b55e48-5807-11e3-8388-b2259682fb3e.jpg)

**Comment by astaxie** [comment]
很明显你运行测试用例的时候没有你是在框架外面，这个运行肯定报错啊，你的AppConfig没有初始化啊

**Comment by meilihao** [comment]
不明白"很明显你运行测试用例的时候没有你是在框架外面"的意思.dao.go中我改用config.NewConfig("ini", "conf/app.conf")初始化,发现运行bee run和bee test,配置文件路径上会差一个"../",这又是怎么回事?

**Comment by meilihao** [comment]
今天更新到1.2,go test运行到beego.AppConfig.String("db_name")不报错,只是取到内容为空

**Comment by jjnainiang** [comment]
func init() {
	beego.LoadAppConfig("ini", "app.conf 文件的路径")
}

在 test 文件内加入 init() 方法
