### ISSUE TITLE
bee 在win下的使用

### ISSUE THREAD

**Issue by summerworm** [astaxie/bee#4]
1.需要添加环境变量 gopath —— D:\Go\bin（安装完bee之后，bee.exe所在目录），不添加这个环境变量，就算是cd到当前目录也不可用。
2.需要新建目录：D:\Go\bin\src
然后就可以用了

**Comment by astaxie** [comment]
gopath这个你必须设置的吧，新建src目录是什么意思？

**Comment by summerworm** [comment]
go1.0.3不是必须的吧？ 只要一个 GOROOT —— D:\Go\ 就可以了

就算添加了环境变量，也不是在任何地方都可以用bee的，会提示：
    can't create application outside of GOPATH
    you first should `cd $GOPATH/src` then use create

必须在 D:\Go\bin\src 目录下才能用bee，所以要先新建一个src

这个不算什么大问题，只是强制了src的位置。

**Comment by astaxie** [comment]
这个是这样设计的

**Comment by astaxie** [comment]
看看你的大小写  

## 

astaxie
已使用 Sparrow (http://www.sparrowmailapp.com/?sig)

在 2013年6月16日星期日，下午5:02，feeloc 写道：
