### ISSUE TITLE
Can't create project in $GOPATH/src sub-folder

### ISSUE THREAD

**Issue by matrixik** [astaxie/bee#6]
Hello,

I would like to create new project in `$GOPATH/src/bitbucket.org/matrixik` sub-folder so that I could import controllers folder with 
`"bitbucket.org/matrixik/beehello/controllers"` 
instead of 
`"beehello/controllers"`

Now I see error:

```
D:\Golibs\my\src\bitbucket.org\matrixik>bee create beehello
can't create application outside of GOPATH
you first should `cd $GOPATH/src` then use create
```

It's not not very high priority, after all I can create app in `$GOPATH/src`, copy it to desired folder and update imports by hand.

Best regards,
Dobrosław Żybort

**Comment by astaxie** [comment]
Now if you want use bee to create project, you should in `$GOPATH/src`, other folder can't support.But you suggest is reasonable. In `$GOPATH/src` sub-folder should support.

**Comment by matrixik** [comment]
On Windows it create now main.go with import looking like:

```
import (
    "\bitbucket.org\matrixik/beehello/controllers"
    "github.com/astaxie/beego"
) 
```

**Comment by astaxie** [comment]
fix it now, update the bee and try again

**Comment by matrixik** [comment]
Working now, thank you.

Best regards,
Dobrosław Żybort
